//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobiUwB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobiUwB.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorzy pragną podziękować wszystkim członkom Informatycznego Koła Naukowego UwB oraz dyrekcji Instytutu Informatyki..
        /// </summary>
        public static string AboutPageGreetingsContent {
            get {
                return ResourceManager.GetString("AboutPageGreetingsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program na licencji MIT..
        /// </summary>
        public static string AboutPageLicenseContent {
            get {
                return ResourceManager.GetString("AboutPageLicenseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorzy.
        /// </summary>
        public static string AboutPageSubtitleAuthors {
            get {
                return ResourceManager.GetString("AboutPageSubtitleAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podziękowania.
        /// </summary>
        public static string AboutPageSubtitleGreetings {
            get {
                return ResourceManager.GetString("AboutPageSubtitleGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencja.
        /// </summary>
        public static string AboutPageSubtitleLicense {
            get {
                return ResourceManager.GetString("AboutPageSubtitleLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programie.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (opiekun).
        /// </summary>
        public static string AboutPageTutorEnding {
            get {
                return ResourceManager.GetString("AboutPageTutorEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacja.
        /// </summary>
        public static string ContactPageLocalization {
            get {
                return ResourceManager.GetString("ContactPageLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string ContactPageTitle {
            get {
                return ResourceManager.GetString("ContactPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korzystasz z 2G.
        /// </summary>
        public static string InternetCheckerToast2g {
            get {
                return ResourceManager.GetString("InternetCheckerToast2g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korzystasz z 3G.
        /// </summary>
        public static string InternetCheckerToastMobile3G {
            get {
                return ResourceManager.GetString("InternetCheckerToastMobile3G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korzystasz z 4G.
        /// </summary>
        public static string InternetCheckerToastMobile4G {
            get {
                return ResourceManager.GetString("InternetCheckerToastMobile4G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utracono połączenie.
        /// </summary>
        public static string InternetCheckerToastNoConnection {
            get {
                return ResourceManager.GetString("InternetCheckerToastNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połączenie kablowe.
        /// </summary>
        public static string InternetCheckerToastPc {
            get {
                return ResourceManager.GetString("InternetCheckerToastPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połączenie z internetem.
        /// </summary>
        public static string InternetCheckerToastTitle {
            get {
                return ResourceManager.GetString("InternetCheckerToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieznane połaczenie.
        /// </summary>
        public static string InternetCheckerToastUnknown {
            get {
                return ResourceManager.GetString("InternetCheckerToastUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korzystasz z WiFi.
        /// </summary>
        public static string InternetCheckerToastWiFi {
            get {
                return ResourceManager.GetString("InternetCheckerToastWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiadomienia MobiUwB..
        /// </summary>
        public static string NotificationsBackgroundAgentDescription {
            get {
                return ResourceManager.GetString("NotificationsBackgroundAgentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie zezwolił aplikacji na działanie w tle..
        /// </summary>
        public static string NotificationsBackgroundAgentNotAvailable {
            get {
                return ResourceManager.GetString("NotificationsBackgroundAgentNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pl-PL.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dzień.
        /// </summary>
        public static string SettingsListItemDay {
            get {
                return ResourceManager.GetString("SettingsListItemDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godz..
        /// </summary>
        public static string SettingsListItemHour {
            get {
                return ResourceManager.GetString("SettingsListItemHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min..
        /// </summary>
        public static string SettingsListItemMinute {
            get {
                return ResourceManager.GetString("SettingsListItemMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Częstotliwość.
        /// </summary>
        public static string SettingsPageCategoryFrequency {
            get {
                return ResourceManager.GetString("SettingsPageCategoryFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od.
        /// </summary>
        public static string SettingsPageCategoryFrom {
            get {
                return ResourceManager.GetString("SettingsPageCategoryFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiadomienia.
        /// </summary>
        public static string SettingsPageCategoryNotifications {
            get {
                return ResourceManager.GetString("SettingsPageCategoryNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakres godzinowy.
        /// </summary>
        public static string SettingsPageCategoryTimeRange {
            get {
                return ResourceManager.GetString("SettingsPageCategoryTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string SettingsPageCategoryTo {
            get {
                return ResourceManager.GetString("SettingsPageCategoryTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zły przedział godzin.
        /// </summary>
        public static string SettingsPageWrongTimeRange {
            get {
                return ResourceManager.GetString("SettingsPageWrongTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wykryto połączenia z Internetem, prosimy spróbować ponownie..
        /// </summary>
        public static string SomethingWrongPageDescription {
            get {
                return ResourceManager.GetString("SomethingWrongPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odśwież.
        /// </summary>
        public static string SomethingWrongPageRefreshRoundButtonText {
            get {
                return ResourceManager.GetString("SomethingWrongPageRefreshRoundButtonText", resourceCulture);
            }
        }
    }
}
